### ISSUE TITLE
I have Invalid Certificate problem.

### ISSUE THREAD

**Issue by Shurazuki** [Gagong/Toshinou-Revamped#26]
I did everything right but i cannot connect any kind of internet sites while using fiddler.

**Comment by Beelzebu** [comment]
Did you added the fiddler ssl cert to your browser?

**Comment by Pendramon** [comment]
Go in Fiddler > Tools > HTTPs > Actions > Reset all Certificates.
Should fix the problem, if it doesn't post back here or better yet ask in discord for faster response.
