### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by cebox1337** [Gagong/Toshinou-Revamped#30]
06.06/07.06.2018 I got stuck at loading screen, was there any DO update?

**Comment by LiamEngland** [comment]
Can i get a beesechurger with that?

**Comment by Xmb99** [comment]
Please new update, doesnt run.

**Comment by lider2697** [comment]
it doesnt work . please update

**Comment by Archangel34637** [comment]
yeah same thing happened to me yesterday stuck at loading screen , probably needs an update

**Comment by ArvinteCristian** [comment]
The developers know this already and they re working on it. Please be patient

**Comment by Bujupah** [comment]
Be patient already lol, they know and they are working on it

**Comment by Archangel34637** [comment]
haha yeah man sorry about that , you are totally right , hope they update
it soon .

2018-06-07 19:17 GMT+03:00 Khalil Mejdi <notifications@github.com>:
