### ISSUE TITLE
Repair on spot

### ISSUE THREAD

**Issue by gambler1996** [Gagong/Toshinou-Revamped#33]
I believe for palladium bot there is needed an option to repair on spot cause after u rep at port bot is never able to reach to palladium zone again so every time u get killed bot is just useless if you are not watching what is going on there. Repping at spot after a certain amount of time for example 30 seconds can make it able for bot to keep working even after you get shot down. Thank you!

**Comment by Gagong** [comment]
After 26.06.2018.
