### ISSUE TITLE
Start using real commit descriptions

### ISSUE THREAD

**Issue by freshstudio** [Gagong/Toshinou-Revamped#44]
Can you tell me why is [this](https://github.com/Gagong/Toshinou-Revamped/commit/9480bb64482f840350b593829902f6106ad77d65) named "For Derka"? Or what does [this](https://github.com/Gagong/Toshinou-Revamped/commit/cc9c20a2557dae83ba89cb17345267e0f77744a8) mean? It looks more like a meme than a open-source project.

**Comment by Gagong** [comment]
AAAhashsdafhs FRESHEK

:D 

I know, but after 26.06 ;d

**Comment by ZerNico** [comment]
It's a dead meme tho
