### ISSUE TITLE
 hybrid alloy collection

### ISSUE THREAD

**Issue by sait4567** [Gagong/Toshinou-Revamped#48]
= - [Blighted Kristallon] = - After about 1 second you will have to scan for <= <Blighted Gygerthrall> => and you must first interrupt it and the bot will go further

>>>>and you have to work together to make sure that you can achieve this<<<<<

**Comment by sait4567** [comment]
Macro Recorder

**Comment by sait4567** [comment]
-

**Comment by Pinianor** [comment]
fucking turk...
