### ISSUE TITLE
Warning?

### ISSUE THREAD

**Issue by Bujupah** [Gagong/Toshinou-Revamped#53]
I just found this, is it possible to detect such a tool like this ? i mean its hard no? i think the only way to find out is that Bigpoint get the access to the executed programs on our PC which is impossible, or by making something tricky on the .swf file no,? >__< 

WARNING: There are rumors from trusted community members that darkorbit is working on a detection method. So please do not use on any accounts you don't want banned. You are warned. If you get banned we are not responsible.

source: https://prnt.sc/jzotaw

**Comment by Markolo95** [comment]
> I just found this, is it possible to detect such a tool like this ? i mean its hard no? 

I think there IS a way to detect bot like toshinou. For example just simply watch the mouse clicks.

> i think the only way to find out is that Bigpoint get the access to the executed programs on our PC which is impossible, or by making something tricky on the .swf file no,? >__<

I dont think that a website have enough authority to collect information about your computer like what other programs are running in the background.

**Comment by Bujupah** [comment]
That's what i thought !
