### ISSUE TITLE
Not working probably game update

### ISSUE THREAD

**Issue by repomen7** [Gagong/Toshinou-Revamped#56]
Hi this morning i found out that bot cant login into game map so i think it is cos of same game update.
im just leting you now.

**Comment by KristianP26** [comment]
You need wait on new bot update bcs darkorbit client was updated.

**Comment by AlphaNayko** [comment]
when to update ?

**Comment by LabodiDavid** [comment]
UPDATE PLS

**Comment by FanatUA** [comment]
Уже у всех обновился , ждем тебя , ты лучше всего!
