### ISSUE TITLE
Not, working

### ISSUE THREAD

**Issue by lionernzm** [Gagong/Toshinou-Revamped#62]
Game dont starting after loading.

**Comment by repomen7** [comment]
Still not working after usinig an updated version from this morning.

**Comment by Photas11** [comment]
It is working for me. I removed old version and replaced it with the new one.

**Comment by azer1992** [comment]
что плохо обнову долга ждать приходится

**Comment by azer1992** [comment]
Люди кто подскажет ошибку 502 HTTP ???

**Comment by azer1992** [comment]
Люди Добрые если кому не трудно помогите настроить почему то после  обновы я не могу запустить мой скайп isaev.ilkin ????

**Comment by repomen7** [comment]
I do it like every time replace everithink and do it again like i do every update but this time it just not working like when game have an update and i got old version. maybe they upload a wrong file or somethink. Can you check it ? i try it on opera and then on chrome and for both its same :/

**Comment by MaxThe** [comment]
for me it works without any problems whatsoever. hm
