### ISSUE TITLE
Problem!

### ISSUE THREAD

**Issue by repomen7** [Gagong/Toshinou-Revamped#70]
For me and some other guys this update still not working its frezz at the logining screen. I post this here cos its said that all issues we are supoust to tell her so i do it last time its not woekoing for every one and i dont get it why ido this like 20 times befor so its not like i dont know what to do. Now i reinstal even filder delete all files instal again add extensions again set it. manage filer rules open https and stil nothink. Its the same problem as befor this update. Can you help me try to find out what it is and why is it doing this? or you will delete this post for the 3 time ?.

**Comment by erythreas34** [comment]
Do you have 5 iq? Or just trolling?
