### ISSUE TITLE
Collect Box When Circle don't work

### ISSUE THREAD

**Issue by FerrariAndrea** [Gagong/Toshinou-Revamped#75]
I tried the new version of the Delta, some things do not seem to work:

- General->Move randomly--> the ship only waiting npc to kill (General->kill nps it's working) and the 
appearance of the boxes to collect them (Box settings->Bonus box  it's working)

- General-> Circle -> The ship do not circle when it engage a npc

- Box settings-> Collect Box When Circle -> The ship do not collect box when it engage a npc

I would like to start studying your masterpiece, to start I'm trying to attack a debug to google chrome for flash. I downloaded and installed the "flashplayer_30_ppapi_debug" version, but the debug option is blocked (in-game->right key->debugger), and i think that the Chrome console is useless with flash, can you tell me the way?

**Comment by azer1992** [comment]
а как делта настроить у меня вопше не  запускает?

**Comment by FerrariAndrea** [comment]
If you write in Russian I find it difficult to understand you, my English is already bad.
If I understood you, to make the bot work you need to use the old version of Delta.

**Comment by azer1992** [comment]
знаете у меня была бета но я не могу старую настроить делта
